TASK 3/config/routes.rb
Rails.application.routes.draw do
  get 'articles/home'

  get 'articles/profil'

  get 'articles/contact'

	root :to => "articles#home"
	resources :articles
	

end

TASK 3/app/models/article.rb
class Article < ActiveRecord::Base
end

TASK 3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

TASK 3/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def home
  end

  def profil
  end

  def contact
  end
end

TASK 3/app/helpers/application_helper.rb
module ApplicationHelper
end

TASK 3/app/views/articles/contact.html.erb
<!DOCTYPE html>
 <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Training Bootstrap</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
	<script src="js/jquery-1.11.1.js"></script>
	<script src="js/bootstrap.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body style="padding-top:60px;">   
<!--bagian navigation-->
	
<div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
           <table  class="table table-hover table-striped display" >          
             <tbody>
               <tr>
                 <td>Email</td>
                 <td><form>
  <fieldset class="form-group">
     <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email Anda">
      </fieldset></form>
  </td>
               </tr>
          <tr>
                 <td>Message</td>
				 <td><fieldset class="form-group">
				 <label for="exampleTextarea"></label>
				 <textarea class="form-control" id="exampleTextarea" rows="3" placeholder="Masukkan Pesan Anda"></textarea>
				 </fieldset></td>
           </tr>
					<tr><td></td><td>
					<button type="submit" class="btn btn-primary">Submit</button></td>
					</tr>
             </tbody>
           </table>
          </div>
        </div>
      </div>
    </div>
	
	
<link href="css/avatar.css " rel="stylesheet ">
<div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
		  <img class="avatar" <%= image_tag "Jellyfish.jpg" %> />
		  
            <h1> RIKU KIRANATAMA </h1>
          </div>
        </div>

TASK 3/app/views/articles/home.html.erb
	<style type="text">
    .navbar-inverse {
    background-color: #3b5998;
    font-size:18px;
    }
</style>

 
    
    <!-- Put Navigation bar here  -->
    <!--Put Content website here -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="container clearfix">
  <div class="row row-offcanvas row-offcanvas-left ">
  <div class="carousel-inner" role="listbox">
    <div class="item active">
		<%= image_tag "Jellyfish.jpg" %>
        <div class="carousel-caption">
	  <h3>Gang di Kota Bandung</h3>
       <p>Ini adalah Slide 3 (Penjelasan)</p>
        ...
      </div>
	  <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
	  <div class="list-group">
		<p>hello saya riku dan saya saat ini akan lulus dari kuliah salam kenal ya. 
	  saya lulusan desain grafis dan saya akan memulai pekerjaan saya sebagai seorang desaigner</p>      
	  </div>
        </div>
	<div class="col-xs-12 col-sm-3 side pull-right sidebar-offcanvas" id="sidebar" role="navigation">
	  <div class="list-group">
		<p>facebook : riku@mail.com</p>
		<p>twitter : riku@mail.com</p>
		<p>telepon: 022-2322332</p>
	  </div>
        </div>
	  </div>
	 
    <div class="item">
		<%= image_tag "Koala.jpg" %>
        <div class="carousel-caption">
    
      </div>
    </div>
	<div class="item" align=center>
		<%= image_tag "Penguins.jpg" %>
        <div class="carousel-caption">
        ...
      </div>
	 </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

 
 

TASK 3/app/views/articles/profil.html.erb
<!DOCTYPE html>
 <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Training Bootstrap</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
	<script src="js/jquery-1.11.1.js"></script>
	<script src="js/bootstrap.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body style="padding-top:60px;">   
<!--bagian navigation-->
    <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <a href="" class = "navbar-brand">Training Bootstrap</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href=home.htm>Home</a></li>
            <li><a href=profil.htm>Profile</a></li>
            <li><a href=contact.htm>Contact</a></li>
          </ul>
        </div>  
      </div>
    </div>

	
<div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
           <table  class="table table-hover table-striped display" >          
             <tbody>
               <tr>
                 <td>Nama</td>
                 <td>Riku</td>
               </tr>
          <tr>
                 <td>Tempat, Tanggal Lahir</td>
                 <td>Jakarta, 22 November 1999</td>
                 <tr><td>Jenis Kelamin</td>
                 <td>Pria</td></tr>
				 <tr><td>Alamat Domisili</td>
				 <td>Alamat Domisili</td></tr>
               </tr>
             </tbody>
           </table>
          </div>
        </div>
      </div>
    </div>

<link href="css/avatar.css " rel="stylesheet ">
<div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
		  <img class="avatar" <%= image_tag "Jellyfish.jpg" %> />
		  
            <h1> RIKU KIRANATAMA </h1>
          </div>
        </div>

TASK 3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>TrainingAplikasi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <a href="" class = "navbar-brand">Training Bootstrap</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'home',articles_home_path %></li>
			<li><%= link_to 'profil',articles_profil_path %></li>
			<li><%= link_to 'contact',articles_contact_path %></li>
            </ul>
        </div>  
      </div>
    </div>

<%= yield %>

</body>
</html>